### PR TITLE
Add INCLUDE_COUNTRY_CODES

### PR DESCRIPTION
**Pull request by edgar-vincent**
This adds an INCLUDE_COUNTRY_CODES feature which forces the connection to a specific list of CCs.

### CODE REVIEW

**Comment by edgar-vincent** [comment]
Drafting this until https://github.com/r3nor/mullvad-tailscale/pull/9 is reviewed.

**Comment by r3nor** [comment]
Hi, I will ask you to wait a bit as I have a new version of the script that will include this feature. Thank you a lot for your PR and I hope you can review this next version.

**Comment by r3nor** [comment]
You can now review the new version, tell me if you find something wrong or to improve! Note that the flags are different for some actions.

**Comment by edgar-vincent** [comment]
Great, I'll do this in a couple hours.

**Comment by edgar-vincent** [comment]
v2 doesn't exactly implement this feature, as it only allow the user to specify a country with an option. I presume users who always want to connect to a specific country won't want to call the script with an extra option each time.

**Pull request closed without merging**
